apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: digitalbank
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
---
# Ingress — production'da LoadBalancer veya Ingress Controller kullan
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digitalbank-ingress
  namespace: digitalbank
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: digitalbank.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
