apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: digitalbank
type: Opaque
stringData:
  # Production'da: kubectl create secret generic jwt-secret --from-literal=JWT_SECRET=<güçlü-secret>
  JWT_SECRET: "DigitalBankSuperSecretKey2024!MustBe256BitsLongForHS256Algorithm"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: digitalbank
type: Opaque
stringData:
  auth-db-password: "auth_pass"
  account-db-password: "account_pass"
  transaction-db-password: "transaction_pass"
  loan-db-password: "loan_pass"
  notification-db-password: "notification_pass"
