apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: digitalbank
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://auth-db-service:5432/auth_db"
  SPRING_DATASOURCE_USERNAME: "auth_user"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  JWT_ACCESS_EXPIRATION: "900000"
  JWT_REFRESH_EXPIRATION: "604800000"
  SERVER_PORT: "8081"
