apiVersion: v1
kind: Service
metadata:
  name: loan-service
  namespace: digitalbank
spec:
  selector:
    app: loan-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
