apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: digitalbank
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://account-db-service:5432/account_db"
  SPRING_DATASOURCE_USERNAME: "account_user"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  SERVER_PORT: "8082"
